#!/usr/bin/env python3
"""
Write `docs/VERIFICATION.md` from what the harness actually found.

Generated rather than hand-written, because a hand-written verification report drifts from the
thing it describes and then becomes a more confident lie than having no report at all. Re-run
`tools/verify/run.sh && python3 tools/verify/report.py` and the document is true again.
"""

import json
import pathlib
from collections import Counter

HERE = pathlib.Path(__file__).resolve().parent
BUILD = HERE / 'build'
ROOT = HERE.parents[1]
OUT = ROOT / 'docs' / 'VERIFICATION.md'

DIFFERENTIAL_LABEL = {
    'AGREE': 'agrees with its brute force',
    'DISAGREE': 'DISAGREES with its brute force',
    'NO_RUNNABLE_BRUTE_FORCE': 'brute force is an excerpt, not a program',
    'NO_COMPARABLE_PAIR': 'the two blocks share no comparable method',
    'UNSUPPORTED_SIGNATURE': 'takes a shape the generator cannot build',
    'SOLUTION_DID_NOT_COMPILE': 'DID NOT COMPILE',
    'DISAGREES_AS_DOCUMENTED': 'disagrees on purpose — the page says this brute force is wrong',
    'FAULT_NOT_REPRODUCED': 'THE DOCUMENTED FAULT NO LONGER REPRODUCES',
    'AGREE_BUT_VACUOUS': 'AGREES, BUT ON INPUTS THAT PROVE NOTHING',
    'NOT_COMPARABLE_BY_DESIGN': 'not comparable — the two answer different questions',
}

EXAMPLE_LABEL = {
    'MATCHES_PAGE': 'matches the examples on its page',
    'MISMATCH': 'DOES NOT match the examples on its page',
    'NOT_REPLAYABLE': 'examples not machine-readable',
    'NO_EXAMPLES': 'no examples',
    'NO_ENTRY_POINT': 'no callable entry point',
    'NOT_COMPILED': 'did not compile',
}


def main() -> int:
    manifest = json.loads((BUILD / 'manifest.json').read_text())
    compile_report = json.loads((BUILD / 'compile-report.json').read_text())
    differential = {row['id']: row for row in json.loads((BUILD / 'differential-report.json').read_text())}
    examples = {row['id']: row for row in json.loads((BUILD / 'examples-report.json').read_text())}

    compiled = set(compile_report['compiled'])
    total = len(manifest)
    compiles = sum(1 for e in manifest if e['optimized']['class'] in compiled)
    agree = sum(1 for r in differential.values() if r['status'] == 'AGREE')
    disagree = sum(1 for r in differential.values() if r['status'] == 'DISAGREE')
    matches = sum(1 for r in examples.values() if r['status'] == 'MATCHES_PAGE')
    mismatch = sum(1 for r in examples.values() if r['status'] == 'MISMATCH')
    trials = sum(r['trials'] for r in differential.values())

    diff_tally = Counter(r['status'] for r in differential.values())
    ex_tally = Counter(r['status'] for r in examples.values())

    lines = []
    w = lines.append

    w('# What has actually been verified')
    w('')
    w('*Generated by `tools/verify/report.py` from the last run of `tools/verify/run.sh`. '
      'Do not edit by hand — re-run it instead.*')
    w('')
    w('This file exists because the problem bank was written by an AI, and its authors checked each')
    w('solution against examples they had themselves written. That is self-consistency, not')
    w('correctness: a wrong solution paired with a wrong expected output agrees with itself')
    w('perfectly. What follows is what an external tool can say about the same code.')
    w('')
    w('## The short version')
    w('')
    w('| | |')
    w('|---|---|')
    w(f'| Solutions that **compile** | **{compiles}/{total}** |')
    w(f'| Solutions that **produce the answers printed on their own page** | **{matches}/{total}** '
      f'({mismatch} mismatch) |')
    w(f'| Solutions that **agree with an independent brute force** on random legal inputs | '
      f'**{agree}/{total}** ({disagree} disagree) |')
    w(f'| Random inputs tried in the differential stage | {trials:,} |')
    w('')
    w('**What none of this proves:** that a solution would pass LeetCode. The problem statements in')
    w('this library are a reconstruction, not a copy, so the *specification itself* is unverified —')
    w('a solution can be a perfect implementation of a subtly wrong problem and everything here')
    w('still goes green. Typing one into a judge remains the only way to know, which is what the')
    w('practice link on every problem page is for.')
    w('')

    w('## The three checks, and what each is worth')
    w('')
    w('**1. Compilation** is the broadest and shallowest. javac has no idea what the author')
    w('intended, so a block that compiles is at least valid Java with consistent types and real')
    w('library calls. Nobody had ever run it over this bank before.')
    w('')
    w('**2. Example replay** runs each solution against the worked examples printed beside it. It')
    w('catches a solution that does not produce the answer its own page claims — a real failure')
    w('mode, since code and examples were written in the same sitting. It cannot catch wrongness')
    w('the examples do not exercise, which is most wrongness: three inputs chosen by the person who')
    w('wrote the code are exactly the three inputs the code was made to satisfy.')
    w('')
    w('**3. Differential testing** is the strong one. Where a problem carries a runnable brute')
    w('force, the two implementations are independent programs for the same specification, run over')
    w('hundreds of random inputs drawn from the problem\'s own stated constraints and required to')
    w('agree exactly. For that to pass while the solution is wrong, the same mistake has to appear')
    w('twice, in two algorithms that share no structure. Its weakness is coverage:')
    w(f'{diff_tally.get("NO_RUNNABLE_BRUTE_FORCE", 0)} problems carry a brute force written as an')
    w('excerpt rather than a program, so there is nothing to test against.')
    w('')

    w('## What it found')
    w('')
    w('Three genuine defects, all in **brute-force** code — which matters more than it sounds,')
    w('because the brute force is the part the reader is shown first and invited to reason about.')
    w('')
    w('**`house-robber-ii`** — the enumeration treats house `i` as adjacent to `(i + 1) % n`. With a')
    w('single house that is the house itself, so it appeared to be its own neighbour and every plan')
    w('was rejected: `rob([9])` returned 0 where the constraints say plainly that "a single house is')
    w('trivially legal". The optimised solution had the `n == 1` case carved out and was right all')
    w('along; the two disagreed on the first trial. Fixed, and the case added to that problem\'s')
    w('common mistakes, because it is the trap any wrap-around adjacency sets.')
    w('')
    w('**`number-of-operations-to-connect`** — the brute force counted how many cables were')
    w('individually redundant, removing each from the *original* graph. That overcounts: a triangle')
    w('has three individually-redundant edges but only one genuine spare, since pulling all three')
    w('collapses it. On 6 computers and 3 cables it reported 3 moves where the answer is -1, because')
    w('6 computers cannot be connected with fewer than 5 cables at all. Fixed by testing each cable')
    w('against what is left rather than against the original.')
    w('')
    w('**`move-zeroes`** — the page\'s "obvious" approach shifted elements down and then stepped the')
    w('index back to re-examine the vacated slot. Once a zero reaches the final position, which is')
    w('inevitable for any input containing one, that step-back lands on the same slot forever: an')
    w('infinite loop on the most ordinary input the problem has. It had never been executed, only')
    w('read, which is exactly the class of defect a reader cannot catch by reading either.')
    w('')
    w('Each was found by the differential stage, and none would have been found by the example')
    w('replay — the examples on all three pages passed throughout.')
    w('')

    w('## Two ways this report could have lied')
    w('')
    w('A green tick is only worth what the test behind it can fail on, and two kinds of tick here')
    w('turned out to be worth nothing until the harness was taught to notice.')
    w('')
    w('**Agreement on inputs that prove nothing.** Seven problems agreed on all 400 trials while')
    w('producing a single distinct answer the whole way through, or throwing on every one. A cycle')
    w('detector was only ever handed acyclic lists, because the list generator could not build a')
    w('cycle; `same-tree` compared two independently random trees, which are never equal; a problem')
    w('about digit strings was fed random letters and returned zero every time. Each was a green')
    w('tick over a test that could not have come out any other way. The runner now counts distinct')
    w('answers and reports **AGREE_BUT_VACUOUS** instead, and the generators for those seven were')
    w('widened until both outcomes actually occur.')
    w('')
    w('**Brute forces that are wrong on purpose.** On four problems the naive approach is not merely')
    w('slow but incorrect, and saying so is the most useful thing the page does: the reader meets the')
    w('implementation they would have written, then meets the input that breaks it. `validate-bst`')
    w('checks each node only against its immediate children; `same-tree` compares traversals with no')
    w('null markers; `coin-change` takes the largest coin that fits; `add-two-numbers` packs the')
    w('digits into a machine integer that overflows. For these the harness **inverts**: disagreement')
    w('is the pass, and unbroken agreement is the failure, reported as **FAULT_NOT_REPRODUCED**.')
    w('')
    w('That inversion guards something nothing else does. If one of these brute forces were later')
    w('tidied into a correct one, every other check in the project would stay green — the content')
    w('validator, the unit tests, the example replay, and a differential test reporting a cheerful')
    w('AGREE — while the page went on asserting a fault that no longer existed, with a')
    w('counterexample that no longer broke anything.')
    w('')

    w('## Where the harness had to be told the rules')
    w('')
    w('The first differential run reported fourteen failures and not one was a defect. They were')
    w('inputs the problems forbid: negative prices fed to a problem constrained to `0 <= prices[i]`,')
    w('empty arrays given to one that says `1 <= nums.length`, values outside `{0,1,2}` handed to')
    w('sort-colors. An implementation owes no sensible behaviour outside its stated domain, and a')
    w('report full of such findings teaches the reader to ignore it.')
    w('')
    w(f'So the generator reads each problem\'s own `constraints` list — {len(json.loads((BUILD / "domains.json").read_text()))}')
    w('problems, of which the parser understands the stated domain for those written as ranges. A')
    w('handful state *structural* preconditions no type-driven generator will hit by chance ("every')
    w('element appears exactly twice except one", "the grid is a permutation of 0..n²−1", "both')
    w('arrays are already sorted"); those have named repairs in `tools/verify/src/Preconditions.java`,')
    w('each quoting the constraint it enforces. Two problems say their answer may be returned in any')
    w('order, and that flag is read from their statements rather than assumed.')
    w('')

    w('## Full results')
    w('')
    w('`compiles` · `examples` · `differential`, one row per problem.')
    w('')
    w('| Problem | Compiles | Own examples | Against brute force |')
    w('|---|---|---|---|')
    for entry in manifest:
        pid = entry['id']
        ok = '✅' if entry['optimized']['class'] in compiled else '❌'
        ex = examples.get(pid, {})
        ex_status = ex.get('status', '?')
        ex_text = EXAMPLE_LABEL.get(ex_status, ex_status)
        if ex_status == 'MATCHES_PAGE':
            ex_text = f'✅ {ex.get("passed", 0)}/{ex.get("total", 0)}'
        elif ex_status == 'MISMATCH':
            ex_text = f'❌ {ex.get("passed", 0)}/{ex.get("total", 0)} — {ex.get("detail", "")}'
        else:
            ex_text = f'— {ex_text}'

        df = differential.get(pid, {})
        df_status = df.get('status', '?')
        if df_status == 'AGREE':
            df_text = f'✅ {df.get("trials", 0)} random inputs'
        elif df_status == 'DISAGREE':
            df_text = f'❌ {df.get("detail", "")}'
        else:
            df_text = f'— {DIFFERENTIAL_LABEL.get(df_status, df_status)}'
        w(f'| `{pid}` | {ok} | {ex_text} | {df_text} |')

    w('')
    w('## Running it yourself')
    w('')
    w('```')
    w('./tools/verify/run.sh          # extract, compile, replay examples, differential test')
    w('python3 tools/verify/report.py # rewrite this document from the results')
    w('```')
    w('')
    w('It exits non-zero if any solution fails to compile, contradicts its own page, or disagrees')
    w('with its brute force, so it belongs in CI if this ever gets one.')
    w('')
    w('## Status tallies')
    w('')
    w('| Example replay | Count |')
    w('|---|---|')
    for status, count in sorted(ex_tally.items(), key=lambda kv: -kv[1]):
        w(f'| {EXAMPLE_LABEL.get(status, status)} | {count} |')
    w('')
    w('| Differential | Count |')
    w('|---|---|')
    for status, count in sorted(diff_tally.items(), key=lambda kv: -kv[1]):
        w(f'| {DIFFERENTIAL_LABEL.get(status, status)} | {count} |')
    w('')

    OUT.write_text('\n'.join(lines) + '\n')
    print(f'[report] wrote {OUT.relative_to(ROOT)} — {compiles}/{total} compile, '
          f'{matches} match their examples, {agree} agree with a brute force')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
